name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --user buildozer cython virtualenv

      - name: Fix Permissions
        run: |
          # This prevents the 'exit code 100' permission error
          sudo chown -R runner:docker /home/runner/work/ui-jumper-mobile/ui-jumper-mobile

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # The '--verbose' flag lets us see exactly where it stops if it fails
          buildozer --verbose android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
